# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  policy:
    image: policy
    build:
      context: .
      dockerfile: Policy.Api/Dockerfile
    ports:
      - 80:80
  customer:
    image: customer
    build:
      context: .
      dockerfile: Customer.Api/Dockerfile
    ports:
      - 32002:80
  claim:
    image: claim
    build:
      context: .
      dockerfile: Claim.Api/Dockerfile
    ports:
      - 32003:80
  payment:
    image: payment
    build:
      context: .
      dockerfile: Payment.Api/Dockerfile
    ports:
      - 32004:80